# Generated by Django 5.0 on 2023-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_car_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
